export enum IconEnum {
  html = 'html',
  css = 'css',
  sass = 'sass',
  tailwind = 'tailwind',
  javaScript = 'javascript',
  typeScript = 'typescript',
  vue = 'vue',
  pinia = 'pinia',
  vite = 'vite',
  git = 'git',
  github = 'github',
  firebase = 'firebase',
  nodejs = 'nodejs',
  mongo = 'mongo',
  web = 'web',
  php = 'php',
  webpack = 'webpack',
  laravel = 'laravel',
  react = 'react',
  mysql = 'mysql',
}
